import Head from "next/head";
import { Box } from "@chakra-ui/react";
import MainNavbar from "../components/group/MainNavbar";
import HomeLayout from "../components/pageLayout/Home";
import { NAVBAR_WIDTH } from "../constants/number";
import { GetServerSideProps, GetServerSidePropsContext } from "next";
import { getSession } from "next-auth/react";

type Props = {};
const Home: React.FC = () => {
  return (
    <Box>
      <Head>
        <title>Sales App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainNavbar />
      <Box pl={NAVBAR_WIDTH}>
        <Box className="min-h-screen" p="6">
          <HomeLayout />
        </Box>
      </Box>
    </Box>
  );
};

export default Home;
