import { Box } from "@chakra-ui/react";
import Head from "next/head";
import React from "react";
import ProfileNavbar from "../components/group/ProfileNavbar";
import { NAVBAR_WIDTH } from "../constants/number";
import ProfileComponent from "../components/pageLayout/Profile";

type Props = {};

const Profile = (props: Props) => {
  return (
    <Box>
      <Head>
        <title>Sales App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfileNavbar />
      <Box pl={NAVBAR_WIDTH}>
        <ProfileComponent />
      </Box>
    </Box>
  );
};

export default Profile;
